AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
   WinstonLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
         LayerName: Winston
         Description: Winston dependencies as an AWS Lambda Layer
         ContentUri: ../dist.zip
         RetentionPolicy: Retain
         CompatibleRuntimes:
            - nodejs12.x
